"""
Companion Manager for RAG Companion System

This module manages multiple companions, user accounts, and provides
the library of RAG companions with their generated content.
"""

from typing import Dict, List, Optional, Any, Union
from dataclasses import dataclass, field
from datetime import datetime, timedelta
import json
import uuid
import logging
import os
from pathlib import Path

from .companion_core import CompanionCore, UserContext
from .personality_engine import PersonalityEngine, PersonalityScores
from .wellbeing_framework import WellbeingFramework

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@dataclass
class UserAccount:
    """User account with associated companions and preferences"""
    user_id: str
    username: str
    email: str
    created_at: datetime
    last_login: datetime
    preferences: Dict[str, Any] = field(default_factory=dict)
    active_companion_id: Optional[str] = None
    companion_ids: List[str] = field(default_factory=list)
    settings: Dict[str, Any] = field(default_factory=dict)
    
    def add_companion(self, companion_id: str) -> None:
        """Add a companion to the user's library"""
        if companion_id not in self.companion_ids:
            self.companion_ids.append(companion_id)
    
    def remove_companion(self, companion_id: str) -> bool:
        """Remove a companion from the user's library"""
        if companion_id in self.companion_ids:
            self.companion_ids.remove(companion_id)
            if self.active_companion_id == companion_id:
                self.active_companion_id = None
            return True
        return False
    
    def set_active_companion(self, companion_id: str) -> bool:
        """Set the active companion for the user"""
        if companion_id in self.companion_ids:
            self.active_companion_id = companion_id
            return True
        return False
    
    def update_login(self) -> None:
        """Update last login time"""
        self.last_login = datetime.now()
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            "user_id": self.user_id,
            "username": self.username,
            "email": self.email,
            "created_at": self.created_at.isoformat(),
            "last_login": self.last_login.isoformat(),
            "preferences": self.preferences,
            "active_companion_id": self.active_companion_id,
            "companion_ids": self.companion_ids,
            "settings": self.settings
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'UserAccount':
        """Create from dictionary"""
        return cls(
            user_id=data["user_id"],
            username=data["username"],
            email=data["email"],
            created_at=datetime.fromisoformat(data["created_at"]),
            last_login=datetime.fromisoformat(data["last_login"]),
            preferences=data.get("preferences", {}),
            active_companion_id=data.get("active_companion_id"),
            companion_ids=data.get("companion_ids", []),
            settings=data.get("settings", {})
        )

@dataclass
class GeneratedContent:
    """Content generated by a companion"""
    content_id: str
    companion_id: str
    user_id: str
    content_type: str  # text, image, audio, etc.
    title: str
    content: str
    metadata: Dict[str, Any]
    created_at: datetime
    tags: List[str] = field(default_factory=list)
    is_public: bool = False
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            "content_id": self.content_id,
            "companion_id": self.companion_id,
            "user_id": self.user_id,
            "content_type": self.content_type,
            "title": self.title,
            "content": self.content,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
            "tags": self.tags,
            "is_public": self.is_public
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'GeneratedContent':
        """Create from dictionary"""
        return cls(
            content_id=data["content_id"],
            companion_id=data["companion_id"],
            user_id=data["user_id"],
            content_type=data["content_type"],
            title=data["title"],
            content=data["content"],
            metadata=data.get("metadata", {}),
            created_at=datetime.fromisoformat(data["created_at"]),
            tags=data.get("tags", []),
            is_public=data.get("is_public", False)
        )

class CompanionManager:
    """
    Manages multiple companions, user accounts, and generated content
    """
    
    def __init__(self, storage_path: str = "./data", openai_api_key: Optional[str] = None):
        self.storage_path = Path(storage_path)
        self.openai_api_key = openai_api_key
        
        # Ensure storage directory exists
        self.storage_path.mkdir(parents=True, exist_ok=True)
        
        # Initialize frameworks
        self.personality_engine = PersonalityEngine()
        self.wellbeing_framework = WellbeingFramework()
        
        # Initialize companions
        self.companions: Dict[str, CompanionCore] = {}
        
        # Load existing companions
        self._load_companions()
        
        logger.info(f"Companion manager initialized with storage path: {storage_path}")
    
    def _initialize_default_companions(self) -> None:
        """Initialize default companions for new installations"""
        default_companions = [
            {
                "name": "Luna",
                "personality_preset": "enthusiastic_supporter",
                "description": "A warm and enthusiastic companion focused on emotional support and motivation"
            },
            {
                "name": "Atlas",
                "personality_preset": "calm_advisor",
                "description": "A thoughtful and reliable companion for goal-setting and problem-solving"
            },
            {
                "name": "Zara",
                "personality_preset": "creative_explorer",
                "description": "An imaginative and curious companion for creative projects and learning"
            },
            {
                "name": "Kai",
                "personality_preset": "reliable_helper",
                "description": "A dependable and organized companion for productivity and habit-building"
            }
        ]
        
        for companion_data in default_companions:
            # Create personality scores based on preset
            personality_scores = self._get_personality_scores_from_preset(companion_data["personality_preset"])
            
            companion = CompanionCore(
                companion_id=str(uuid.uuid4()),
                name=companion_data["name"],
                personality_scores=personality_scores
            )
            self.companions[companion.companion_id] = companion
        
        self._save_data()
        logger.info("Default companions initialized")
    
    def create_companion(self, name: str, personality_preset: str = "balanced", 
                        companion_id: Optional[str] = None) -> str:
        """Create a new companion with specified personality"""
        try:
            # Generate companion ID if not provided
            if not companion_id:
                companion_id = str(uuid.uuid4())
            
            # Get personality scores from preset
            personality_scores = self._get_personality_scores_from_preset(personality_preset)
            
            # Create companion core
            companion = CompanionCore(
                companion_id=companion_id,
                name=name,
                personality_scores=personality_scores,
                wellbeing_framework=self.wellbeing_framework,
                data_dir=str(self.storage_path / companion_id)
            )
            
            # Store companion
            self.companions[companion_id] = companion
            
            # Save companion metadata
            self._save_companion_metadata(companion_id, name, personality_preset)
            
            logger.info(f"Created companion: {name} ({companion_id}) with {personality_preset} personality")
            return companion_id
            
        except Exception as e:
            logger.error(f"Failed to create companion: {e}")
            raise
    
    def _get_personality_scores_from_preset(self, preset: str) -> PersonalityScores:
        """Convert personality preset to PersonalityScores object"""
        try:
            # Define personality presets (1.0-7.0 scale)
            presets = {
                "balanced": PersonalityScores(
                    honesty_humility=4.0,
                    emotionality=4.0,
                    extraversion=4.0,
                    agreeableness=4.0,
                    conscientiousness=4.0,
                    openness=4.0
                ),
                "extroverted": PersonalityScores(
                    honesty_humility=4.0,
                    emotionality=3.5,
                    extraversion=6.5,
                    agreeableness=4.5,
                    conscientiousness=4.0,
                    openness=4.5
                ),
                "introverted": PersonalityScores(
                    honesty_humility=4.5,
                    emotionality=4.5,
                    extraversion=2.5,
                    agreeableness=4.0,
                    conscientiousness=4.5,
                    openness=5.0
                ),
                "conscientious": PersonalityScores(
                    honesty_humility=5.0,
                    emotionality=3.5,
                    extraversion=3.5,
                    agreeableness=4.0,
                    conscientiousness=6.5,
                    openness=4.0
                ),
                "creative": PersonalityScores(
                    honesty_humility=4.0,
                    emotionality=4.5,
                    extraversion=4.5,
                    agreeableness=4.0,
                    conscientiousness=3.5,
                    openness=6.5
                ),
                "empathetic": PersonalityScores(
                    honesty_humility=5.5,
                    emotionality=5.5,
                    extraversion=4.0,
                    agreeableness=6.5,
                    conscientiousness=4.0,
                    openness=4.5
                )
            }
            
            if preset not in presets:
                logger.warning(f"Unknown personality preset: {preset}, using balanced")
                preset = "balanced"
            
            return presets[preset]
            
        except Exception as e:
            logger.error(f"Failed to get personality scores from preset: {e}")
            # Return balanced as fallback
            return PersonalityScores(
                honesty_humility=4.0,
                emotionality=4.0,
                extraversion=4.0,
                agreeableness=4.0,
                conscientiousness=4.0,
                openness=4.0
            )
    
    def create_user_account(self, username: str, email: str, 
                           initial_preferences: Dict[str, Any] = None) -> Dict:
        """Create a new user account"""
        # Check if username or email already exists
        for user in self.users.values():
            if user.username == username:
                return {
                    "success": False,
                    "error": "Username already exists",
                    "message": "Please choose a different username."
                }
            if user.email == email:
                return {
                    "success": False,
                    "error": "Email already registered",
                    "message": "This email is already associated with an account."
                }
        
        # Create new user account
        user_id = str(uuid.uuid4())
        user = UserAccount(
            user_id=user_id,
            username=username,
            email=email,
            created_at=datetime.now(),
            last_login=datetime.now(),
            preferences=initial_preferences or {},
            settings={
                "notifications_enabled": True,
                "privacy_level": "standard",
                "data_sharing": False
            }
        )
        
        self.users[user_id] = user
        
        # Assign a default companion
        default_companion_id = list(self.companions.keys())[0]
        user.add_companion(default_companion_id)
        user.set_active_companion(default_companion_id)
        
        self._save_data()
        
        logger.info(f"Created user account: {username} (ID: {user_id})")
        
        return {
            "success": True,
            "user_id": user_id,
            "message": f"Welcome {username}! Your account has been created successfully.",
            "default_companion_id": default_companion_id
        }
    
    def authenticate_user(self, username: str, password_hash: str = None) -> Dict:
        """Authenticate a user (simplified for demo - would use proper auth in production)"""
        for user in self.users.values():
            if user.username == username:
                user.update_login()
                self._save_data()
                
                return {
                    "success": True,
                    "user_id": user.user_id,
                    "username": user.username,
                    "active_companion_id": user.active_companion_id,
                    "message": f"Welcome back, {username}!"
                }
        
        return {
            "success": False,
            "error": "User not found",
            "message": "Invalid username or password."
        }
    
    def get_user_companions(self, user_id: str) -> Dict:
        """Get all companions associated with a user"""
        if user_id not in self.users:
            return {
                "success": False,
                "error": "User not found",
                "message": "User account not found."
            }
        
        user = self.users[user_id]
        user_companions = {}
        
        for companion_id in user.companion_ids:
            if companion_id in self.companions:
                companion = self.companions[companion_id]
                user_companions[companion_id] = {
                    "name": companion.name,
                    "personality_summary": companion.personality_engine.get_personality_summary(),
                    "capabilities": companion.get_capabilities()["capabilities"],
                    "is_active": companion_id == user.active_companion_id,
                    "created_at": companion.created_at.isoformat(),
                    "last_active": companion.last_active.isoformat()
                }
        
        return {
            "success": True,
            "companions": user_companions,
            "total_companions": len(user_companions),
            "active_companion_id": user.active_companion_id,
            "message": f"You have {len(user_companions)} companions in your library."
        }
    
    def create_custom_companion(self, user_id: str, name: str, 
                               personality_scores: Dict[str, float] = None,
                               personality_preset: str = None) -> Dict:
        """Create a custom companion for a user"""
        if user_id not in self.users:
            return {
                "success": False,
                "error": "User not found",
                "message": "User account not found."
            }
        
        try:
            # Create companion with specified personality
            if personality_scores:
                scores = PersonalityScores(**personality_scores)
                companion = CompanionCore(name=name, personality_scores=scores)
            elif personality_preset:
                companion = CompanionCore(name=name, personality_preset=personality_preset)
            else:
                # Default personality
                companion = CompanionCore(name=name)
            
            # Add to user's library
            user = self.users[user_id]
            user.add_companion(companion.companion_id)
            
            # Save to storage
            self.companions[companion.companion_id] = companion
            self._save_data()
            
            logger.info(f"Created custom companion '{name}' for user {user_id}")
            
            return {
                "success": True,
                "companion_id": companion.companion_id,
                "name": companion.name,
                "personality_summary": companion.personality_engine.get_personality_summary(),
                "message": f"Your custom companion '{name}' has been created successfully!"
            }
            
        except Exception as e:
            logger.error(f"Error creating custom companion: {e}")
            return {
                "success": False,
                "error": str(e),
                "message": "Failed to create custom companion. Please try again."
            }
    
    def switch_active_companion(self, user_id: str, companion_id: str) -> Dict:
        """Switch the user's active companion"""
        if user_id not in self.users:
            return {
                "success": False,
                "error": "User not found",
                "message": "User account not found."
            }
        
        user = self.users[user_id]
        
        if companion_id not in user.companion_ids:
            return {
                "success": False,
                "error": "Companion not in library",
                "message": "This companion is not in your library."
            }
        
        if companion_id not in self.companions:
            return {
                "success": False,
                "error": "Companion not found",
                "message": "Companion not found in system."
            }
        
        # Switch active companion
        user.set_active_companion(companion_id)
        self._save_data()
        
        companion = self.companions[companion_id]
        
        logger.info(f"User {user_id} switched to companion: {companion.name}")
        
        return {
            "success": True,
            "active_companion_id": companion_id,
            "companion_name": companion.name,
            "message": f"Switched to {companion.name}! How can I help you today?"
        }
    
    def get_active_companion(self, user_id: str) -> Optional[CompanionCore]:
        """Get the user's active companion"""
        if user_id not in self.users:
            return None
        
        user = self.users[user_id]
        if not user.active_companion_id:
            return None
        
        return self.companions.get(user.active_companion_id)
    
    def store_generated_content(self, companion_id: str, user_id: str, 
                               content_type: str, title: str, content: str,
                               metadata: Dict[str, Any] = None, tags: List[str] = None) -> Dict:
        """Store content generated by a companion"""
        if companion_id not in self.companions:
            return {
                "success": False,
                "error": "Companion not found",
                "message": "Companion not found in system."
            }
        
        if user_id not in self.users:
            return {
                "success": False,
                "error": "User not found",
                "message": "User account not found."
            }
        
        # Create generated content record
        content_id = str(uuid.uuid4())
        generated_content = GeneratedContent(
            content_id=content_id,
            companion_id=companion_id,
            user_id=user_id,
            content_type=content_type,
            title=title,
            content=content,
            metadata=metadata or {},
            created_at=datetime.now(),
            tags=tags or []
        )
        
        # Store content
        self.generated_content[content_id] = generated_content
        
        # Save to storage
        self._save_data()
        
        logger.info(f"Stored generated content: {title} (ID: {content_id})")
        
        return {
            "success": True,
            "content_id": content_id,
            "message": f"Content '{title}' has been saved to your library."
        }
    
    def get_user_generated_content(self, user_id: str, content_type: str = None,
                                  companion_id: str = None, limit: int = 50) -> Dict:
        """Get content generated for a user"""
        if user_id not in self.users:
            return {
                "success": False,
                "error": "User not found",
                "message": "User account not found."
            }
        
        # Filter content by user
        user_content = []
        for content in self.generated_content.values():
            if content.user_id == user_id:
                # Apply filters
                if content_type and content.content_type != content_type:
                    continue
                if companion_id and content.companion_id != companion_id:
                    continue
                
                user_content.append(content.to_dict())
        
        # Sort by creation date (newest first)
        user_content.sort(key=lambda x: x["created_at"], reverse=True)
        
        # Apply limit
        if limit:
            user_content = user_content[:limit]
        
        return {
            "success": True,
            "content": user_content,
            "total_count": len(user_content),
            "message": f"Found {len(user_content)} pieces of generated content."
        }
    
    def search_generated_content(self, user_id: str, query: str, 
                                content_type: str = None, tags: List[str] = None) -> Dict:
        """Search through user's generated content"""
        if user_id not in self.users:
            return {
                "success": False,
                "error": "User not found",
                "message": "User account not found."
            }
        
        # Get user's content first
        user_content_result = self.get_user_generated_content(user_id)
        if not user_content_result["success"]:
            return user_content_result
        
        user_content = user_content_result["content"]
        search_results = []
        
        query_lower = query.lower()
        
        for content in user_content:
            # Check if content matches search criteria
            matches_query = (
                query_lower in content["title"].lower() or
                query_lower in content["content"].lower() or
                any(query_lower in tag.lower() for tag in content["tags"])
            )
            
            matches_type = not content_type or content["content_type"] == content_type
            matches_tags = not tags or any(tag in content["tags"] for tag in tags)
            
            if matches_query and matches_type and matches_tags:
                search_results.append(content)
        
        return {
            "success": True,
            "search_results": search_results,
            "total_results": len(search_results),
            "query": query,
            "message": f"Found {len(search_results)} results for '{query}'."
        }
    
    def delete_generated_content(self, user_id: str, content_id: str) -> Dict:
        """Delete generated content (only if owned by user)"""
        if user_id not in self.users:
            return {
                "success": False,
                "error": "User not found",
                "message": "User account not found."
            }
        
        if content_id not in self.generated_content:
            return {
                "success": False,
                "error": "Content not found",
                "message": "Content not found in system."
            }
        
        content = self.generated_content[content_id]
        
        # Check ownership
        if content.user_id != user_id:
            return {
                "success": False,
                "error": "Access denied",
                "message": "You can only delete your own content."
            }
        
        # Delete content
        deleted_title = content.title
        del self.generated_content[content_id]
        
        # Save to storage
        self._save_data()
        
        logger.info(f"Deleted content: {deleted_title} (ID: {content_id})")
        
        return {
            "success": True,
            "message": f"Content '{deleted_title}' has been deleted."
        }
    
    def get_companion_performance(self, companion_id: str) -> Dict:
        """Get performance metrics for a companion"""
        if companion_id not in self.companions:
            return {
                "success": False,
                "error": "Companion not found",
                "message": "Companion not found in system."
            }
        
        companion = self.companions[companion_id]
        performance = companion.get_performance_summary()
        
        # Add content generation stats
        content_count = sum(1 for content in self.generated_content.values() 
                           if content.companion_id == companion_id)
        
        performance["generated_content_count"] = content_count
        
        return {
            "success": True,
            "performance": performance,
            "message": f"Performance summary for {companion.name}."
        }
    
    def _load_data(self) -> None:
        """Load data from storage files"""
        try:
            # Load users
            users_file = self.storage_path / "users.json"
            if users_file.exists():
                with open(users_file, 'r') as f:
                    users_data = json.load(f)
                    for user_data in users_data.values():
                        user = UserAccount.from_dict(user_data)
                        self.users[user.user_id] = user
            
            # Load companions
            companions_file = self.storage_path / "companions.json"
            if companions_file.exists():
                with open(companions_file, 'r') as f:
                    companions_data = json.load(f)
                    for companion_data in companions_data.values():
                        companion = CompanionCore.from_dict(companion_data)
                        self.companions[companion.companion_id] = companion
            
            # Load generated content
            content_file = self.storage_path / "generated_content.json"
            if content_file.exists():
                with open(content_file, 'r') as f:
                    content_data = json.load(f)
                    for content_item in content_data.values():
                        content = GeneratedContent.from_dict(content_item)
                        self.generated_content[content.content_id] = content
            
            logger.info("Data loaded from storage")
            
        except Exception as e:
            logger.error(f"Error loading data: {e}")
    
    def _save_data(self) -> None:
        """Save data to storage files"""
        try:
            # Save users
            users_file = self.storage_path / "users.json"
            users_data = {user_id: user.to_dict() for user_id, user in self.users.items()}
            with open(users_file, 'w') as f:
                json.dump(users_data, f, indent=2)
            
            # Save companions
            companions_file = self.storage_path / "companions.json"
            companions_data = {comp_id: companion.to_dict() 
                             for comp_id, companion in self.companions.items()}
            with open(companions_file, 'w') as f:
                json.dump(companions_data, f, indent=2)
            
            # Save generated content
            content_file = self.storage_path / "generated_content.json"
            content_data = {content_id: content.to_dict() 
                           for content_id, content in self.generated_content.items()}
            with open(content_file, 'w') as f:
                json.dump(content_data, f, indent=2)
            
            logger.info("Data saved to storage")
            
        except Exception as e:
            logger.error(f"Error saving data: {e}")
    
    def get_system_stats(self) -> Dict:
        """Get overall system statistics"""
        return {
            "total_users": len(self.users),
            "total_companions": len(self.companions),
            "total_generated_content": len(self.generated_content),
            "storage_path": str(self.storage_path),
            "system_status": "operational"
        }
