"""
Multimedia Storage Service for RAG Companion System

Handles storage and retrieval of multimedia content generated by MCP tools
and user uploads, with database integration for metadata tracking.
"""

import os
import hashlib
import uuid
import mimetypes
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple
import logging
from dataclasses import dataclass

from database import RAGDatabase

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@dataclass
class MultimediaContent:
    """Multimedia content metadata"""
    content_id: str
    user_id: str
    content_type: str  # 'image', 'audio', 'video', 'document'
    file_path: str
    file_name: str
    file_size: int
    mime_type: str
    content_hash: str
    session_id: Optional[str] = None
    turn_id: Optional[str] = None
    metadata: Dict[str, Any] = None
    is_generated: bool = False
    generation_tool: Optional[str] = None
    generation_prompt: Optional[str] = None
    tags: List[str] = None
    created_at: datetime = None

class MultimediaStorageService:
    """
    Service for managing multimedia content storage and retrieval
    """
    
    def __init__(self, storage_dir: str = "multimedia", database: RAGDatabase = None):
        self.storage_dir = Path(storage_dir)
        self.storage_dir.mkdir(parents=True, exist_ok=True)
        
        # Create subdirectories for different content types
        for content_type in ['images', 'audio', 'video', 'documents']:
            (self.storage_dir / content_type).mkdir(exist_ok=True)
        
        self.database = database
        
        logger.info(f"Multimedia storage service initialized at: {self.storage_dir}")
    
    def _get_content_type_dir(self, content_type: str) -> Path:
        """Get storage directory for specific content type"""
        type_mapping = {
            'image': 'images',
            'audio': 'audio', 
            'video': 'video',
            'document': 'documents'
        }
        
        dir_name = type_mapping.get(content_type, 'documents')
        return self.storage_dir / dir_name
    
    def _detect_content_type(self, file_path: str, mime_type: str = None) -> str:
        """Detect content type from file path and MIME type"""
        if mime_type:
            if mime_type.startswith('image/'):
                return 'image'
            elif mime_type.startswith('audio/'):
                return 'audio'
            elif mime_type.startswith('video/'):
                return 'video'
            elif mime_type.startswith('text/') or mime_type.startswith('application/'):
                return 'document'
        
        # Fallback to file extension
        ext = Path(file_path).suffix.lower()
        if ext in ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp']:
            return 'image'
        elif ext in ['.mp3', '.wav', '.ogg', '.m4a', '.flac']:
            return 'audio'
        elif ext in ['.mp4', '.avi', '.mov', '.mkv', '.webm']:
            return 'video'
        else:
            return 'document'
    
    def _generate_content_hash(self, file_path: str) -> str:
        """Generate SHA-256 hash of file content"""
        hash_sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                hash_sha256.update(chunk)
        return hash_sha256.hexdigest()
    
    def store_file(self, source_path: str, user_id: str, content_type: str = None,
                  session_id: str = None, turn_id: str = None, metadata: Dict = None,
                  is_generated: bool = False, generation_tool: str = None,
                  generation_prompt: str = None, tags: List[str] = None) -> str:
        """
        Store a file in the multimedia storage system
        
        Args:
            source_path: Path to source file
            user_id: User identifier
            content_type: Type of content (auto-detected if None)
            session_id: Conversation session ID
            turn_id: Conversation turn ID
            metadata: Additional metadata
            is_generated: Whether content was generated by MCP tool
            generation_tool: Name of MCP tool that generated content
            generation_prompt: Prompt used to generate content
            tags: Content tags for categorization
            
        Returns:
            Content ID of stored file
        """
        try:
            source_path = Path(source_path)
            if not source_path.exists():
                raise FileNotFoundError(f"Source file not found: {source_path}")
            
            # Detect content type if not specified
            if not content_type:
                mime_type, _ = mimetypes.guess_type(str(source_path))
                content_type = self._detect_content_type(str(source_path), mime_type)
            
            # Generate content ID and determine storage path
            content_id = str(uuid.uuid4())
            content_dir = self._get_content_type_dir(content_type)
            file_extension = source_path.suffix
            storage_filename = f"{content_id}{file_extension}"
            storage_path = content_dir / storage_filename
            
            # Copy file to storage
            import shutil
            shutil.copy2(source_path, storage_path)
            
            # Get file info
            file_size = storage_path.stat().st_size
            mime_type, _ = mimetypes.guess_type(str(storage_path))
            content_hash = self._generate_content_hash(str(storage_path))
            
            # Create content object
            content = MultimediaContent(
                content_id=content_id,
                user_id=user_id,
                content_type=content_type,
                file_path=str(storage_path),
                file_name=storage_filename,
                file_size=file_size,
                mime_type=mime_type or 'application/octet-stream',
                content_hash=content_hash,
                session_id=session_id,
                turn_id=turn_id,
                metadata=metadata or {},
                is_generated=is_generated,
                generation_tool=generation_tool,
                generation_prompt=generation_prompt,
                tags=tags or [],
                created_at=datetime.now()
            )
            
            # Store in database if available
            if self.database:
                self.database.store_multimedia_content(
                    content_id=content.content_id,
                    user_id=content.user_id,
                    content_type=content.content_type,
                    file_path=content.file_path,
                    file_name=content.file_name,
                    file_size=content.file_size,
                    mime_type=content.mime_type,
                    content_hash=content.content_hash,
                    session_id=content.session_id,
                    turn_id=content.turn_id,
                    metadata=content.metadata,
                    is_generated=content.is_generated,
                    generation_tool=content.generation_tool,
                    generation_prompt=content.generation_prompt,
                    tags=content.tags
                )
            
            logger.info(f"Stored multimedia content: {content_id} ({content_type})")
            return content_id
            
        except Exception as e:
            logger.error(f"Error storing file: {e}")
            raise
    
    def store_mcp_generated_content(self, file_path: str, user_id: str, 
                                  generation_tool: str, generation_prompt: str,
                                  session_id: str = None, turn_id: str = None,
                                  metadata: Dict = None, tags: List[str] = None) -> str:
        """
        Store content generated by MCP tools
        
        Args:
            file_path: Path to generated file
            user_id: User identifier
            generation_tool: Name of MCP tool
            generation_prompt: Prompt used for generation
            session_id: Conversation session ID
            turn_id: Conversation turn ID
            metadata: Additional metadata
            tags: Content tags
            
        Returns:
            Content ID of stored file
        """
        return self.store_file(
            source_path=file_path,
            user_id=user_id,
            session_id=session_id,
            turn_id=turn_id,
            metadata=metadata,
            is_generated=True,
            generation_tool=generation_tool,
            generation_prompt=generation_prompt,
            tags=tags or []
        )
    
    def get_content(self, content_id: str) -> Optional[MultimediaContent]:
        """Retrieve multimedia content by ID"""
        if not self.database:
            return None
        
        try:
            db_content = self.database.get_multimedia_content(content_id)
            if not db_content:
                return None
            
            return MultimediaContent(
                content_id=db_content["content_id"],
                user_id=db_content["user_id"],
                content_type=db_content["content_type"],
                file_path=db_content["file_path"],
                file_name=db_content["file_name"],
                file_size=db_content["file_size"],
                mime_type=db_content["mime_type"],
                content_hash=db_content["content_hash"],
                session_id=db_content["session_id"],
                turn_id=db_content["turn_id"],
                metadata=db_content["metadata"],
                is_generated=db_content["is_generated"],
                generation_tool=db_content["generation_tool"],
                generation_prompt=db_content["generation_prompt"],
                tags=db_content["tags"],
                created_at=db_content["created_at"]
            )
        except Exception as e:
            logger.error(f"Error retrieving content: {e}")
            return None
    
    def get_user_content(self, user_id: str, content_type: str = None,
                        limit: int = 50, offset: int = 0) -> List[MultimediaContent]:
        """Get multimedia content for a user"""
        if not self.database:
            return []
        
        try:
            db_contents = self.database.get_user_multimedia_content(
                user_id=user_id,
                content_type=content_type,
                limit=limit,
                offset=offset
            )
            
            return [
                MultimediaContent(
                    content_id=content["content_id"],
                    user_id=content["user_id"],
                    content_type=content["content_type"],
                    file_path=content["file_path"],
                    file_name=content["file_name"],
                    file_size=content["file_size"],
                    mime_type=content["mime_type"],
                    content_hash=content["content_hash"],
                    session_id=content["session_id"],
                    turn_id=content["turn_id"],
                    metadata=content["metadata"],
                    is_generated=content["is_generated"],
                    generation_tool=content["generation_tool"],
                    generation_prompt=content["generation_prompt"],
                    tags=content["tags"],
                    created_at=content["created_at"]
                )
                for content in db_contents
            ]
        except Exception as e:
            logger.error(f"Error retrieving user content: {e}")
            return []
    
    def delete_content(self, content_id: str) -> bool:
        """Delete multimedia content and file"""
        try:
            content = self.get_content(content_id)
            if not content:
                return False
            
            # Delete file
            file_path = Path(content.file_path)
            if file_path.exists():
                file_path.unlink()
            
            # TODO: Remove from database when delete method is implemented
            logger.info(f"Deleted multimedia content: {content_id}")
            return True
            
        except Exception as e:
            logger.error(f"Error deleting content: {e}")
            return False
    
    def get_storage_stats(self) -> Dict[str, Any]:
        """Get storage statistics"""
        try:
            stats = {
                'total_files': 0,
                'total_size': 0,
                'by_type': {}
            }
            
            for content_type in ['images', 'audio', 'video', 'documents']:
                type_dir = self.storage_dir / content_type
                if type_dir.exists():
                    files = list(type_dir.glob('*'))
                    size = sum(f.stat().st_size for f in files if f.is_file())
                    
                    stats['by_type'][content_type] = {
                        'count': len(files),
                        'size': size
                    }
                    stats['total_files'] += len(files)
                    stats['total_size'] += size
            
            return stats
            
        except Exception as e:
            logger.error(f"Error getting storage stats: {e}")
            return {}
    
    def cleanup_orphaned_files(self) -> int:
        """Remove files that don't have database records"""
        if not self.database:
            return 0
        
        try:
            cleaned_count = 0
            
            # Get all files in storage
            all_files = []
            for content_type in ['images', 'audio', 'video', 'documents']:
                type_dir = self.storage_dir / content_type
                if type_dir.exists():
                    all_files.extend(type_dir.glob('*'))
            
            # Check each file against database
            for file_path in all_files:
                if file_path.is_file():
                    # Extract content ID from filename
                    content_id = file_path.stem
                    
                    # Check if exists in database
                    db_content = self.database.get_multimedia_content(content_id)
                    if not db_content:
                        # Orphaned file, delete it
                        file_path.unlink()
                        cleaned_count += 1
                        logger.info(f"Cleaned up orphaned file: {file_path}")
            
            logger.info(f"Cleanup completed: {cleaned_count} files removed")
            return cleaned_count
            
        except Exception as e:
            logger.error(f"Error during cleanup: {e}")
            return 0
    
    # NEW: pgvector integration methods
    
    async def store_content_with_embedding(self, source_path: str, user_id: str, 
                                         content_description: str, embedding: List[float],
                                         content_type: str = None, session_id: str = None,
                                         turn_id: str = None, metadata: Dict = None,
                                         is_generated: bool = False, generation_tool: str = None,
                                         generation_prompt: str = None, tags: List[str] = None) -> str:
        """
        Store multimedia content with vector embedding for semantic search
        
        Args:
            source_path: Path to source file
            user_id: User identifier
            content_description: Text description for vector embedding
            embedding: Vector embedding of the content description
            content_type: Type of content (auto-detected if None)
            session_id: Conversation session ID
            turn_id: Conversation turn ID
            metadata: Additional metadata
            is_generated: Whether content was generated by MCP tool
            generation_tool: Name of MCP tool that generated content
            generation_prompt: Prompt used to generate content
            tags: Content tags for categorization
            
        Returns:
            Content ID of stored file
        """
        try:
            # First store the file normally
            content_id = self.store_file(
                source_path=source_path,
                user_id=user_id,
                content_type=content_type,
                session_id=session_id,
                turn_id=turn_id,
                metadata=metadata,
                is_generated=is_generated,
                generation_tool=generation_tool,
                generation_prompt=generation_prompt,
                tags=tags
            )
            
            # Then store the description and embedding in pgvector table
            if self.database:
                await self.database.store_multimedia_embedding(
                    content_id=content_id,
                    user_id=user_id,
                    description=content_description,
                    embedding=embedding,
                    content_type=content_type or self._detect_content_type(source_path),
                    metadata=metadata or {}
                )
            
            return content_id
            
        except Exception as e:
            logger.error(f"Error storing content with embedding: {e}")
            raise
    
    async def search_multimedia_by_similarity(self, query_embedding: List[float], 
                                            user_id: str = None, content_type: str = None,
                                            top_k: int = 5) -> List[Dict[str, Any]]:
        """
        Search multimedia content using vector similarity
        
        Args:
            query_embedding: Vector embedding of search query
            user_id: Filter by specific user (optional)
            content_type: Filter by content type (optional)
            top_k: Number of results to return
            
        Returns:
            List of similar multimedia content with similarity scores
        """
        if not self.database:
            return []
        
        try:
            results = await self.database.search_multimedia_embeddings(
                query_embedding=query_embedding,
                user_id=user_id,
                content_type=content_type,
                top_k=top_k
            )
            
            # Enrich results with file information
            enriched_results = []
            for result in results:
                content = self.get_content(result["content_id"])
                if content:
                    enriched_results.append({
                        **result,
                        "file_path": content.file_path,
                        "file_name": content.file_name,
                        "file_size": content.file_size,
                        "mime_type": content.mime_type,
                        "is_generated": content.is_generated,
                        "generation_tool": content.generation_tool,
                        "tags": content.tags
                    })
            
            return enriched_results
            
        except Exception as e:
            logger.error(f"Error searching multimedia by similarity: {e}")
            return []
    
    async def get_content_recommendations(self, user_id: str, content_id: str = None,
                                        content_type: str = None, top_k: int = 5) -> List[Dict[str, Any]]:
        """
        Get content recommendations based on user's content history
        
        Args:
            user_id: User identifier
            content_id: Use specific content as reference (optional)
            content_type: Filter by content type (optional)
            top_k: Number of recommendations to return
            
        Returns:
            List of recommended content
        """
        if not self.database:
            return []
        
        try:
            # Get user's recent content
            user_content = self.get_user_content(user_id, content_type=content_type, limit=10)
            
            if not user_content:
                return []
            
            # Use the most recent content or specified content as reference
            reference_content = None
            if content_id:
                reference_content = self.get_content(content_id)
            
            if not reference_content:
                reference_content = user_content[0]
            
            # Get embedding for reference content
            embedding = await self.database.get_multimedia_embedding(reference_content.content_id)
            if not embedding:
                return []
            
            # Find similar content
            similar_content = await self.search_multimedia_by_similarity(
                query_embedding=embedding,
                user_id=user_id,
                content_type=content_type,
                top_k=top_k + 1  # +1 to exclude the reference content
            )
            
            # Filter out the reference content
            recommendations = [
                content for content in similar_content 
                if content["content_id"] != reference_content.content_id
            ][:top_k]
            
            return recommendations
            
        except Exception as e:
            logger.error(f"Error getting content recommendations: {e}")
            return []
    
    async def store_multimedia_embedding(self, content_id: str, user_id: str,
                                       description: str, embedding: List[float],
                                       content_type: str, metadata: Dict = None):
        """
        Store multimedia content embedding in pgvector table
        
        Args:
            content_id: Content identifier
            user_id: User identifier
            description: Text description of the content
            embedding: Vector embedding
            content_type: Type of content
            metadata: Additional metadata
        """
        if not self.database:
            return
        
        try:
            await self.database.store_multimedia_embedding(
                content_id=content_id,
                user_id=user_id,
                description=description,
                embedding=embedding,
                content_type=content_type,
                metadata=metadata or {}
            )
            logger.info(f"Stored embedding for content: {content_id}")
        except Exception as e:
            logger.error(f"Error storing multimedia embedding: {e}")
    
    async def get_multimedia_embedding(self, content_id: str) -> Optional[List[float]]:
        """Get vector embedding for multimedia content"""
        if not self.database:
            return None
        
        try:
            return await self.database.get_multimedia_embedding(content_id)
        except Exception as e:
            logger.error(f"Error getting multimedia embedding: {e}")
            return None
